# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "user-frontend.fullname" . }}-nginx-config
# data:
#   default.conf: |
#     server {
#       listen 80;
#       server_name localhost;

#       root /usr/share/nginx/html;
#       index index.html;

#       location / {
#         try_files $uri /index.html;
#       }

#       location /api/ {
#         proxy_pass http://{{ default "backend" .Values.backend.serviceName }}:{{ default 8080 .Values.backend.port }}/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_http_version 1.1;
#         proxy_set_header Connection "";
#         proxy_redirect off;
#       }
#     }

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-frontend.fullname" . }}-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html;
      }

      location /api/ {
        proxy_pass http://{{ .Values.backend.serviceName }}:{{ .Values.backend.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_redirect off;
      }
    }


