apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html;
      }

      # Proxy API requests to backend inside cluster
      location /api/ {
        proxy_pass http://{{ .Release.Name }}-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin "*";
      }
    }
