# {{- if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-frontend
#   annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
# spec:
#   {{- if .Values.ingress.className }}
#   ingressClassName: {{ .Values.ingress.className }}
#   {{- end }}
#   rules:
#     {{- range .Values.ingress.hosts }}
#     - host: {{ .host }}
#       http:
#         paths:
#           {{- range .paths }}
#           - path: {{ . }}
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ $.Release.Name }}-frontend
#                 port:
#                   number: {{ $.Values.service.port }}
#           {{- end }}
#     {{- end }}
#   {{- if .Values.ingress.tls }}
#   tls:
#   {{ toYaml .Values.ingress.tls | nindent 4 }}
#   {{- end }}
# {{- end }}

{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
  annotations: {{ toYaml .Values.route.annotations | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
{{- end }}
