{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-admin-frontend
  annotations: {{ toYaml .Values.route.annotations | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-admin-frontend
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
{{- end }}
