apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-backend.fullname" . }}
  labels:
    app: {{ include "admin-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admin-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-backend.name" . }}
    spec:
      containers:
        - name: admin-backend
          image: {{ printf "%s:%s" (default "nginx" .Values.image.repository) (default "latest" .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: EMBEDDING_ENDPOINT
              value: "{{ .Values.env.EMBEDDING_ENDPOINT }}"
            - name: METADATA_DB_URL
              value: "{{ .Values.env.METADATA_DB_URL }}"
            - name: CHUNK_URL
              value: "{{ .Values.env.CHUNK_URL }}"
            - name: VECTOR_DB_ENDPOINT
              value: "{{ .Values.env.VECTOR_DB_ENDPOINT }}"
            - name: DEPLOYED_INDEX_ID
              value: "{{ .Values.env.DEPLOYED_INDEX_ID }}"
            - name: PROJECT_ID
              value: "{{ .Values.env.PROJECT_ID }}"
            - name: REGION
              value: "{{ .Values.env.REGION }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/keys/{{ .Values.gcpServiceAccountKeyFile }}" 
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          
          volumeMounts:
            - name: gcp-sa
              mountPath: {{ .Values.gcpServiceAccount.mountPath }}
              readOnly: true  
      volumes:
        - name: gcp-sa
          secret:
            secretName: {{ .Values.gcpServiceAccount.secretName }}
