# {{- if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "admin-backend.fullname" . }}
#   annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
# spec:
#   ingressClassName: {{ .Values.ingress.className | default "" }}
#   rules:
#   {{- range .Values.ingress.hosts }}
#     - host: {{ .host }}
#       http:
#         paths:
#         {{- range .paths }}
#           - path: {{ . }}
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{  include "admin-backend.fullname"  $ }}
#                 port:
#                   number: {{ $.Values.service.port }}
#         {{- end }}
#   {{- end }}
#   {{- if .Values.ingress.tls }}
#   tls:
#   {{- toYaml .Values.ingress.tls | nindent 4 }}
#   {{- end }}
# {{- end }}

{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "admin-backend.fullname" . }}
  annotations: {{ toYaml .Values.route.annotations | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "admin-backend.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
  host: {{ .Values.route.host | default "" }}
{{- end }}
